### ISSUE TITLE
Viterbi approximation doesn't produce proper output

### ISSUE THREAD

**Issue by starcolon** [Sumolari/hmm#1]
Hi Sumolari,

I've checked out "hmm" library with my node.js app, initializing with a very simple samples but the Viterbi approximation doesn't seem to work. Following is my sample snippets to train the model:
(Given this.hmm = require('hmm.js');)

var _model = new this.hmm(
		['red','yellow','green'],		// States
		'green',						// Final state
		['go','stop'],					// Observation symbols (emissions)
		{'red':0.8,'green':0.2},		// Initial state probabilities
		{								// State transitions
			'go':{'go':0.3,'stop':0.7},
			'stop':{'stop':0.8,'go':0.2}
		},
		{								// State emissions
			'red':{'stop':0.9,'go':0.1},
			'yellow':{'stop':0.5,'go':0.5},
			'green':{'go':1}
		}
	);

	var testSequence = ['go','stop','go'];

	// Probability of states 
	console.log('Generation prob: '+_model.generationProbability(testSequence));

--------------------------
The resultant Viterbi path and approximated probability is always undefined and absolutely zero accordingly. I've thought my samples were too complicated at the first place so I tried your sample as given in the README.md. It doesn't work though. I can't train the model.

Please can you give me advice how to train and use the model properly?

**Comment by Sumolari** [comment]
First of all, apologies for replying this so late.

I think there are a couple of wrong things here, the first is that your transition matrix uses symbols (`go`, `stop`) instead of states (`red`, `yellow`, `green`), so I tried your example with a different transition matrix:

```javascript
var _model = new this.hmm(
	[ 'red', 'yellow', 'green' ], // States
	'green', // Final state
	[ 'go', 'stop' ], // Observation symbols (emissions)
	{
		'red': 0.8,
		'green': 0.2
	}, // Initial state probabilities
	{ // State transitions
		'green': {
			'yellow': 0.3,
			'green': 0.7
		},
		'yellow': {
			'stop': 0.8,
			'yellow': 0.2
		},
		'red': {
			'red': 0.6,
			'green': 0.4
		}
	}, { // State emissions
		'red': {
			'stop': 0.9,
			'go': 0.1
		},
		'yellow': {
			'stop': 0.5,
			'go': 0.5
		},
		'green': {
			'go': 1
		}
	}
);
```

Its forward probability didn't work either but its Viterbi approximation did work so I checked it further and found that there's a bug in forward probability method: it only takes into account as initial state the most probable one instead of all of them.

I've updated the method and fixed the issue.

I'll update the repo later with your example as an additional test case.

**Comment by starcolon** [comment]
@Sumolari No worry, glad it helps despite an example mistake. Thanks for looking into this too.
